<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-CRFERR4" ignored="1" name="Personal Loan" tests="5" failures="1" timestamp="27 Dec 2019 05:48:32 GMT" time="0.103" errors="0">
  <testcase name="pLoan" time="0.009" classname="test.day2"/>
  <testcase name="loginAPIHomeLoan" time="0.01" classname="test.day4"/>
  <testcase name="demo" time="0.044" classname="test.day1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day1.demo(day1.java:19)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- demo -->
  <testcase name="mobileLoginHomeLoan" time="0.02" classname="test.day4"/>
  <testcase name="webLoginHomeLoan" time="0.011" classname="test.day4"/>
  <testcase name="secondTest" time="0.0" classname="test.day1">
    <ignored/>
  </testcase> <!-- secondTest -->
</testsuite> <!-- Personal Loan -->
